### ISSUE TITLE
Question: How to find out why S F8 and A F8 aren't working?

### ISSUE THREAD

**Issue by TheFern2** [felixhummel/setcolors.vim#1]
I just installed ctags on my system, and I noticed F8 was mapped to setcolors, I had forgotten since I use the same theme for so long, but now I want to switch, but only the next theme shortcut works. F8. I have a very simple configuration only setcolors, nerdtree, and tagbar for shortcuts.

Doing map command and shortcut yields the following:
```
n  <F8>        * :call NextColor(1)<CR>
n  <S-F8>      * :call NextColor(-1)<CR>
n  <M-F8>      * :call NextColor(0)<CR> 
```

List of plugins just in case it helps:
```
Plug 'scrooloose/nerdtree'
Plug 'flazz/vim-colorschemes'
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-fugitive', {'tag': 'v2.3'}  "downgraded to version 2.3 via git tags to fix branch visibility
Plug 'easymotion/vim-easymotion'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'deoplete-plugins/deoplete-jedi'
Plug 'vimlab/split-term.vim'
Plug 'felixhummel/setcolors.vim' "This plugin goes to a next color scheme with F8
Plug 'majutsushi/tagbar'
```

Thank you!

**Comment by felixhummel** [comment]
Hi!

I just tried it: both F8 and Shift+F8 work for me, though Alt+F8 does not. I believe Alt+F8 is captured by my shell. :D
Have you tried it without any other plugins?

Shortcuts look the same on my machine:
```
n  <M-F8>      * :call NextColor(0)<CR>
n  <S-F8>      * :call NextColor(-1)<CR>
n  <F8>        * :call NextColor(1)<CR>
```

**Comment by TheFern2** [comment]
I've disabled all plugins but SetColors and ColorSchemes, and Alt and Shift F8 still doesn't work. Tried in different terminals with bash and fish shells. No worries, I'll try to remap and see what happens.
